### ISSUE TITLE
AD 2003 query should be different

### ISSUE THREAD

**Issue by 123dev** [reighnman/Graylog_Content_Pack_Active_Directory_Auditing#2]
Initially reported at [marketplace:](https://marketplace.graylog.org/addons/750b88ea-67f7-47b1-9a6c-cbbc828d9e25) was asked to log at github.

With Active Directory 2003, the search queries need to be adapted.
This part does not apply to AD 2003.

_AND facility:Microsoft\-Windows\-Security\-Auditing_

**Comment by reighnman** [comment]
I'll pull out the facility specification on next update

**Comment by 123dev** [comment]
Thanks reighnman
