### ISSUE TITLE
After importing the pack nothing happened

### ISSUE THREAD

**Issue by mbuyukkarakas** [reighnman/Graylog_Content_Pack_Active_Directory_Auditing#3]
Hello.

I downloaded and imported the pack to my GL 1.2.0. It imported successfully. But after this, nothing happened and I dont see any difference in my GL. No additional dashboard, no inputs, no new streams..

Thank you.
Mehmet

**Comment by shiyamk** [comment]
ya same. am i missing anything?

Thank you,
Kamal

**Comment by lennartkoopmann** [comment]
You also have to apply it in a second step. After importing it will appear in your list of content packs.

**Comment by shiyamk** [comment]
Hi,
i see "Active Directory, Windows, Operating Systems, Security" under Content Packs, but i cannot enable or do anything with it.

Thank you,
Kamal

**Comment by reighnman** [comment]
Can you upload a screenshot?

**Comment by fabiojvalente** [comment]
I have also the same problem, a screenshot is useless because nothing happens when I click on the content pack name

**Comment by shiyamk** [comment]
![graylog - content packs 2015-12-04 10-16-40](https://cloud.githubusercontent.com/assets/13827793/11587285/2819138c-9a70-11e5-84cf-c8c0bfad484f.png)

**Comment by shiyamk** [comment]
clicking on that doesn't do anything

**Comment by mbuyukkarakas** [comment]
I coundnt find any solution, than I reinstalled everything on a fresh
CentOS7 with lastest version. It worked and I could import it and see the
dashboards.

fyi.

On Fri, Dec 4, 2015 at 12:17 PM, shiyamk notifications@github.com wrote:

> clicking on that doesn't do anything
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/reighnman/Graylog_Content_Pack_Active_Directory_Auditing/issues/3#issuecomment-161929739
> .

## 

---

Alice -  "Bana hangi yoldan gitmem gerektigini söyler misin?"
"Bu neyi istedigine ve neye ulasmaya çalistigina bagli" dedi kedi
"Sey, bilmem ki ??? " dedi Alice
"O zaman hangi yoldan gittigin farketmez" dedi kedi.

Alice Harikalar Diyarinda

**Comment by reighnman** [comment]
@shiyamk when you click on the category does it even drop down to show the actual plugin?  Does the Web Servers category drop down?

@lennartkoopmann might be able to chime in, I've never seen this before and can't reproduce on 1.2.2

**Comment by reighnman** [comment]
If you're still having issues importing, you could open it directly and create the necessary components by hand.  Hopefully whatever bug is causing this will be resolved in 2.0

**Comment by reighnman** [comment]
I will look into this with the 2.0 release.
