### ISSUE TITLE
unable to see any Authentication attempts

### ISSUE THREAD

**Issue by nilzor1** [reighnman/Graylog_Content_Pack_Active_Directory_Auditing#4]
Hi,

In GPO I enabled the Audit Account Logon Events, Audit Account Management, Audit Logon Events, Audit Object Access, Audit Policy Change and Audit System Events but nothing coming trough...

It seems to show in the event log but is not populated on the dashboard

**Comment by reighnman** [comment]
What log shipper are you using and version?
