### ISSUE TITLE
Graylog 3.0 Support

### ISSUE THREAD

**Issue by spejosh** [reighnman/Graylog_Content_Pack_Active_Directory_Auditing#6]
Please update pack to support GL >=3.0.

**Comment by ScriptByScript** [comment]
I would support this as well, our deployment will be staying at 2.5.1 until this gets updated or somebody else comes by to update it.

**Comment by chris-y** [comment]
The easiest solution is for somebody who imported the content pack previously and then upgraded to v3.0, to recreate the content pack through the GUI (re-downloading it doesn't work).  Unfortunately I happened upon this problem after I'd deleted all the content or I'd do it myself.

**Comment by gabrotheanswer** [comment]
News for the update pack to support GL >= 3.0?
I have newly installed this version and i'm unable to use this content pack...thank you

**Comment by spejosh** [comment]
Try at your own risk.  Should work as I basically copied this and updated for GL3.  https://github.com/spejosh/SonicWall3CP

**Comment by reighnman** [comment]
Released an updated version for 3.0 but also moved to winlogbeats so would require some modifications.
