### ISSUE TITLE
Unable to upload as a content

### ISSUE THREAD

**Issue by misterbeublelisss** [reighnman/Graylog_Content_Pack_Active_Directory_Auditing#7]
Hi,

I tried to upload the file AD_Auditing_for_Graylog_3.0_content_pack and it didn't work.  The same if I rename the file as json.

I use Graylog 3 and my nxlog is setup properly, I now just need the content pack to be add.

Thanks

**Comment by reighnman** [comment]
Please see the new winlogbeats version or one that was forked for nxlog on 3.0
