### ISSUE TITLE
Error importing content pack

### ISSUE THREAD

**Issue by RemyDePoorter** [reighnman/Graylog_Content_Pack_Active_Directory_Auditing#8]
Error importing content pack, please ensure it is a valid JSON file. Check your Graylog logs for more information.<br /><small>Null id at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1138, column: 1] (through reference chain: org.graylog2.contentpacks.model.AutoValue_LegacyContentPack$Builder["id"])</small>

**Comment by gabrielmorin1** [comment]
Got the same error. Tried to remove the first line : `"id":null,` which seems to be the issue. Now I have this error :
`Error importing content pack, please ensure it is a valid JSON file. Check your Graylog logs for more information.
class org.graylog2.contentpacks.model.AutoValue_LegacyContentPack cannot be cast to class org.graylog2.contentpacks.model.ContentPackV1 (org.graylog2.contentpacks.model.AutoValue_LegacyContentPack and org.graylog2.contentpacks.model.ContentPackV1 are in unnamed module of loader 'app')`
